language: node_js
sudo: false
node_js: 6
install:
  - npm install
script:
  - npm run build-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  on:
    branch: master
